# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Sat Sep 14 17:34:15 PDT 2013
#
#/ usage: rundeck-plugin:node-step  --command <>  --module <> [ --dir <>] 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {

    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --command) rerun_option_check $# $1; COMMAND=$2 ; shift ;;
            --module) rerun_option_check $# $1; MODULE=$2 ; shift ;;
            --dir) rerun_option_check $# $1; DIR=$2 ; shift ;;
            # help option
            -|--*?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.

    # Check required options are set
    [ -z "$COMMAND" ] && { echo >&2 "missing required option: --command" ; return 2 ; }
    [ -z "$MODULE" ] && { echo >&2 "missing required option: --module" ; return 2 ; }
    # If option variables are declared exportable, export them.

    #
    return 0
}


# Initialize the options variables to null.
COMMAND=
MODULE=
DIR=


